### ISSUE TITLE
faq.i3wm.org is down

### ISSUE THREAD

**Issue by deltaphi** [i3/faq.i3wm.org#1]
The FAQ-part of the website, http://faq.i3wm.org is down and has been for a few days now. Google is teasing me with previews of responses to all kinds of problems I'm having with my i3 install, but neither google nor archive.org have a cached version available.

Please bring back faq.i3wm.org!

Regards
deltaphi

**Comment by stapelberg** [comment]
Sorry, didn’t see this back then, but the issue was reported and addressed, hence closing.
